# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - init: bun install && bun run build
    command: bun run start

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public

